Proper Radio Channels for Borgs
TheSwain/Fulpstation pull request #196
Opened 2019-12-28 22:52 UTC by Surrealaser

## About The Pull Request

Borgs now gain access to role appropriate radio channels:

Medborgs get access to Medical.
Peacekeepers and Secborgs get access to Security.
Engiborgs get access to Engineering.
Mining borgs get access to Mining.

All other borgs get access to Service.

## Why It's Good For The Game

Helps borgs do their job by allowing them to be in better communication with their department and take appropriate cues.

## Changelog
:cl:
add: Borgs now gain access to role appropriate radio channels.
/:cl:

2020-01-08 23:54 UTC, Kokojos commented
Quality of life ++.
Worth it to merge.

2020-01-09 17:27 UTC, TheSwain commented
Okay gonna add this in, just needs a conflict resolve and we're good

2020-01-10 02:55 UTC, remove32 commented
doesnt seem to be working 
![image](https://user-images.githubusercontent.com/27014495/72122037-58cdac00-3322-11ea-8d5b-47e99a3b3e8c.png)

2020-01-10 02:55 UTC, remove32 requested changes

2020-01-10 02:55 UTC, remove32 commented on code/zFulpstationCode/fulp_overwrite_vars.dm
> +	radio = /obj/item/radio/borg/medical
typo

2020-01-10 10:08 UTC, Surrealaser commented
Conflicts and issues should be fixed

2020-01-12 01:55 UTC, remove32 commented
can you tick the new file in the dme

2020-01-13 06:07 UTC, Surrealaser commented
@remove32 I mean they were ticked in the version I saved and uploaded

2020-01-13 06:27 UTC, Surrealaser commented
https://i.imgur.com/9dqwJ4C.png

2020-01-14 20:11 UTC, Surrealaser commented
@TheSwain @remove32 This should be ready for merge.

2020-01-15 02:00 UTC, remove32 approved these changes

2020-01-15 02:01 UTC, merged