Remove Intergalactic Common from Ash Walkers
TheSwain/Fulpstation pull request #244
Opened 2020-01-23 22:12 UTC by Shadowtail117

## About The Pull Request

Ash walkers will now only be able to speak Draconic. For now, the language isn't completely blocked but that can be modified if needed.

## Why It's Good For The Game

Ash walkers live in Lavaland and don't work for/know what Nanotransen is. They should only know their own species-specific language and not be able to communicate with humans that they've never seen before. Plus, this might add some incentive for diplomatic relations, since now one needs a lizardperson or universal recorder to talk with them. 

## Changelog
:cl:
tweak: Ash Walkers can no longer communicate with crew members using Intergalactic Common. Nanotransen recommends using lizardperson crewmembers for diplomatic discussions with this race.
/:cl:

2020-01-30 05:28 UTC, remove32 commented
Do this on /datum/language_holder/lizard/ash instead
set a blocked_languages var on it, like swarmer gets

2020-01-31 00:30 UTC, Shadowtail117 commented
I would but ash walkers aren't their own species, they are just reskinned lizardpeople. I can't overwrite their language holders without making them into an entirely new species, I don't think.

While the current method is by no means efficient it does get the job done. Unless there's a way to overwrite the holder outside of the mob declaration I doubt there's any other solution.

2020-01-31 00:32 UTC, Shadowtail117 commented
Disregard my last (deleted) comment, I didn't see the lizardpeople species file. Making the change now.

2020-01-31 00:32 UTC, remove32 commented
![image](https://user-images.githubusercontent.com/27014495/73502518-dff4c980-438e-11ea-97b5-5651e8837b7d.png)
change language_holder.dm

2020-01-31 00:33 UTC, Shadowtail117 commented
Ye ye, but I didn't see how their species file makes a distinction for ash walkers. I thought they were direct reskins of lizardpeople which would have made overwriting the language holder impossible.

2020-01-31 00:38 UTC, Shadowtail117 commented
Should be good to go now.

2020-01-31 04:40 UTC, remove32 commented
dont really need to test this one...

2020-01-31 04:40 UTC, remove32 approved these changes

2020-01-31 04:41 UTC, remove32 requested changes
actually, can you please wrap these lines in comments saying that this is a change for fulpstation? cite the PR number if you'd please

2020-02-01 00:39 UTC, remove32 approved these changes

2020-02-09 00:57 UTC, merged