Pengu's winter coats. V3.
TheSwain/Fulpstation pull request #259
Opened 2020-02-07 01:27 UTC by Homingpenguins

## About The Pull Request
The third time ive done this. Adds 4 winter coats.
Chem, Gene, Barkeep, and Lawyer.
Thanks to Jo, YouTubeBoy, and BeardlessJo for making the Lawyer, Barkeep, and Genetic coats respectively.

## Why It's Good For The Game
It get us further to the goal of having winter coats for all jobs.

## Changelog
:cl:
add: files for organization.
imageadd: added some icons and images : the 5 dmis
icons>Fulpicons>Penguins_cove>Winter_Coat_Pile> (the 5 dmis)
code: changed some code : 
code>vendor>wardrobe.dm (A /tg/ file)
code>Fulpcode>wintercoats.dm (code for winter coats
/:cl:

2020-02-10 21:54 UTC, Shadowtail117 requested changes
All items in the game are lowercase. These winter coats being capitalized is a glaring contradiction.

Other than that, these look fine.

2020-02-10 21:54 UTC, Shadowtail117 commented on code/FulpstationCode/wintercoats.dm
> +	name = "\improper Lawyer's winter coat"
```suggestion
	name = "\improper lawyer's winter coat"
```
All other items are lowercase. Let's maintain consistency.

2020-02-10 21:54 UTC, Shadowtail117 commented on code/FulpstationCode/wintercoats.dm
> +	name = "\improper Bartender's winter coat"
```suggestion
	name = "\improper bartender's winter coat"
```
See above.

2020-02-10 21:54 UTC, Shadowtail117 commented on code/FulpstationCode/wintercoats.dm
> +	name = "\improper Chemist's winter coat"
```suggestion
	name = "\improper chemist's winter coat"
```
See above.

2020-02-10 21:54 UTC, Shadowtail117 commented on code/FulpstationCode/wintercoats.dm
> +	name = "\improper Geneticist's winter coat"
```suggestion
	name = "\improper geneticist's winter coat"
```
See above.

2020-02-10 21:56 UTC, Homingpenguins commented on code/FulpstationCode/wintercoats.dm
> +	name = "\improper Geneticist's winter coat"
fixed

2020-02-10 21:56 UTC, Homingpenguins commented on code/FulpstationCode/wintercoats.dm
> +	name = "\improper Chemist's winter coat"
fixed

2020-02-10 21:56 UTC, Homingpenguins commented on code/FulpstationCode/wintercoats.dm
> +	name = "\improper Bartender's winter coat"
fixed

2020-02-10 21:56 UTC, Homingpenguins commented on code/FulpstationCode/wintercoats.dm
> +	name = "\improper Lawyer's winter coat"
fixed

2020-02-10 21:56 UTC, Shadowtail117 approved these changes

2020-02-10 21:56 UTC, Homingpenguins commented
thanks

2020-02-18 23:55 UTC, TheSwain commented
@Homingpenguins okay to merge this, one of the standards we use when adding objects to existing TG lists is to put them somewhere above the end of the list. basically, any time an item appears in a vending machine or anything like that, it can't be the last thing in the list or we'll get merge conflicts. if you can move them up a few entries any time they're added to the world, that'll make us all set

2020-02-19 21:41 UTC, closed without merging