fixes the cybersun captain missing a jumpsuit
TheSwain/Fulpstation pull request #345
Opened 2020-05-12 07:25 UTC by ErwinSnowden

## About The Pull Request
Fixes the captain to actually be playable without wasting a majority of their ammo to break open lockers. Re-adds their jumpsuit, might be the wrong jumpsuit.

## Why It's Good For The Game
I like playing as this role and this change was not documented and I can't bother trying to track it down and revert it.

## Changelog
:cl:
fix: The Cybersun Captain now spawns with a jumpsuit again, not sure how that was removed.
/:cl:

2020-05-14 07:54 UTC, EgorDinamit commented
Dude, you can like, open lockers with your ID card, you know?

2020-05-14 18:15 UTC, EgorDinamit reviewed
Change outfit's name here and in the spawner's datum.
It will copy part of basic crew outfit.

2020-05-14 18:15 UTC, EgorDinamit commented on code/game/objects/structures/ghost_role_spawners.dm
>  /datum/outfit/syndicatespace/syndicaptain
```suggestion
/datum/outfit/syndicatespace/syndicrew/syndicaptain
```

2020-05-14 18:22 UTC, EgorDinamit commented on code/game/objects/structures/ghost_role_spawners.dm
>  /datum/outfit/syndicatespace/syndicaptain
And replace outfit var with it in "/obj/effect/mob_spawn/human/syndicatespace/captain" part, at line 673.

2020-05-14 23:02 UTC, ErwinSnowden commented
This would result in the captain getting extra gear, to note, night vision and an extra pistol. Not something I'm keen on doing because this is a fix, not a re-balance.

2020-05-15 10:35 UTC, EgorDinamit commented
He is supposed to get everything basic crew gets, with an exception for pistol.

2020-05-15 17:29 UTC, EgorDinamit requested changes
Make captain's outfit copy crew outfit and place Stechkin APS in l_pocket, instead of the backpack.

2020-05-17 12:09 UTC, EgorDinamit commented
I'll fix it in and add some other administrative features to Cybersun in #356

2020-05-23 08:12 UTC, closed without merging