Halloween 2020
TheSwain/Fulpstation pull request #515
Opened 2020-10-27 14:44 UTC by GuillaumePrata

## About The Pull Request
Adds the community event Halloween costumes.

## Why It's Good For The Game
Something something event.

## Changelog
:cl: Guillaume Prata/ The Community 
add: Added multiple costumes
del: Removed some broken costumes
tweak: tweaked the Halloween event from last year
fix: fixed some costumes, Rip Shrek
/:cl:

2020-10-27 19:48 UTC, GoldenAlpharex commented
Yes

2021-07-24 16:56 UTC, SgtHunk commented
Looks good!

2021-07-24 17:14 UTC, SgtHunk requested changes

2021-07-24 17:14 UTC, SgtHunk commented on code/FulpstationCode/halloween_costumes/2019/jo_costumes.dm
> +	name = "Hotdog"
probably should be lowercase

2021-07-24 17:14 UTC, SgtHunk commented on code/FulpstationCode/halloween_costumes/2019/jo_costumes.dm
> +	name = "Hotdog hat"
same here

2021-07-24 17:14 UTC, SgtHunk commented on code/FulpstationCode/halloween_costumes/2019/jo_costumes.dm
> +	name = "Ketchup"
and here

2021-07-24 17:14 UTC, SgtHunk commented on code/FulpstationCode/halloween_costumes/2019/jo_costumes.dm
> +	name = "Ketchup hat"
and here

2021-07-24 17:14 UTC, SgtHunk commented on code/FulpstationCode/halloween_costumes/2019/jo_costumes.dm
> +	name = "Mustard"
and here

2021-07-24 17:14 UTC, SgtHunk commented on code/FulpstationCode/halloween_costumes/2019/jo_costumes.dm
> +	name = "Mustard hat"
and here

2021-07-24 17:14 UTC, SgtHunk commented on code/FulpstationCode/halloween_costumes/2019/jo_costumes.dm
> +	name = "Angel dress"
and here

2021-07-24 17:14 UTC, SgtHunk commented on code/FulpstationCode/halloween_costumes/2019/jo_costumes.dm
> +	name = "Angel halo"
and here

2021-07-24 17:14 UTC, SgtHunk commented on code/FulpstationCode/halloween_costumes/2019/jo_costumes.dm
> +	desc = "The one the only Devil."
...and here.
Also description is a bit weird, should be changed.

2021-07-24 17:14 UTC, SgtHunk commented on code/FulpstationCode/halloween_costumes/2019/jo_costumes.dm
> +	desc = "The one the only Devil."
same here

2021-07-24 17:14 UTC, SgtHunk commented on code/FulpstationCode/halloween_costumes/2019/jo_costumes.dm
> +	name = "Cat suit"
and here

2021-07-24 17:14 UTC, SgtHunk commented on code/FulpstationCode/halloween_costumes/2019/jo_costumes.dm
> +	name = "Cat hat"
and here

2021-07-24 17:14 UTC, SgtHunk commented on code/FulpstationCode/halloween_costumes/2019/jo_costumes.dm
> +	desc = "The insides of a pumpkin a awkwardly warm and slimy."
same here, and description needs to be changed

2021-07-24 17:14 UTC, SgtHunk commented on code/FulpstationCode/halloween_costumes/2019/jo_costumes.dm
> +	desc = "The top of a pumpkin on the top of your head."
same here

2021-07-24 17:14 UTC, SgtHunk commented on code/FulpstationCode/halloween_costumes/2019/jo_costumes.dm
> +	name = "Skeleton"
lowercase, also should have a better name

2021-07-24 17:14 UTC, SgtHunk commented on code/FulpstationCode/halloween_costumes/2019/jo_costumes.dm
> +	desc = "A skull on your face."
same as last comment, also description is weird

2021-07-24 17:14 UTC, SgtHunk commented on code/FulpstationCode/halloween_costumes/2019/jo_costumes.dm
> +	desc = "An unwieldy set of 8 limbs"
name, and description has no punctuation.

2021-07-24 17:14 UTC, SgtHunk commented on code/FulpstationCode/halloween_costumes/2019/jo_costumes.dm
> +	name = "witch"
name shouldn't be just "witch"

2021-07-24 17:14 UTC, SgtHunk commented on code/FulpstationCode/halloween_costumes/2019/jo_costumes.dm
> +	name = "Witch Head"
lowercase, also weird name

2021-07-24 17:14 UTC, SgtHunk commented on code/FulpstationCode/halloween_costumes/2019/jo_costumes.dm
> +	name = "Sailor moon leotard"
lowercase, also maybe more subtle

2021-07-24 17:14 UTC, SgtHunk commented on code/FulpstationCode/halloween_costumes/2019/jo_costumes.dm
> +	name = "Sailor moon wig"
lowercase and subtleness

2021-07-24 17:14 UTC, SgtHunk commented on code/FulpstationCode/halloween_costumes/2019/jo_costumes.dm
> +	desc = "In the name I will Punish you!"
Grammar also name

2021-07-24 17:14 UTC, SgtHunk commented on code/FulpstationCode/halloween_costumes/2019/jo_costumes.dm
> +	desc = "Boots for fighting evil by moonlight."
Same here

2021-07-24 17:14 UTC, SgtHunk commented on code/FulpstationCode/halloween_costumes/2019/jo_costumes.dm
> +	name = "Tuxedo"
lowercase and name

2021-07-24 17:14 UTC, SgtHunk commented on code/FulpstationCode/halloween_costumes/2019/jo_costumes.dm
> +	name = "Top hat"
same here

2021-07-24 17:14 UTC, SgtHunk commented on code/FulpstationCode/halloween_costumes/2019/jo_costumes.dm
> +	desc = "Don't prick your finger on that rose"
lowercase and change description

2021-07-24 17:14 UTC, SgtHunk commented on code/FulpstationCode/halloween_costumes/2019/jo_costumes.dm
> +	name = "Dress shoes"
lowercase

2021-07-24 17:14 UTC, SgtHunk commented on code/FulpstationCode/halloween_costumes/2019/jo_costumes.dm
> +	desc = "Dress shoes for a dapper tux."
epic copypaste fail

2021-07-24 17:14 UTC, SgtHunk commented on code/FulpstationCode/halloween_costumes/2019/joseph_joestar.dm
> +	desc = "Fingerless, to let you better pull tricks out of nowhere."
description's a bit weird

2021-07-24 17:14 UTC, SgtHunk commented on code/FulpstationCode/halloween_costumes/2019/zombie_rider.dm
> +	fulp_item = TRUE //I don't know if this is necessary but WHATEVER
name also fulp item does nothing

2021-07-24 17:14 UTC, SgtHunk commented on code/FulpstationCode/halloween_costumes/2020/2020_event.dm
> +	desc = "It looks like a box wrapped in some spooky paper"
punctuation

2021-07-24 17:14 UTC, SgtHunk commented on code/FulpstationCode/halloween_costumes/2020/columbia.dm
> +	name = "Columbia's suit"
lowercase

2021-07-24 17:14 UTC, SgtHunk commented on code/FulpstationCode/halloween_costumes/2020/columbia.dm
> +	name = "Columbia's hat"
lowercase

2021-07-24 17:14 UTC, SgtHunk commented on code/FulpstationCode/halloween_costumes/2020/columbia.dm
> +	name = "Columbia's jacket"
lowercase

2021-07-24 17:14 UTC, SgtHunk commented on code/FulpstationCode/halloween_costumes/2020/columbia.dm
> +	name = "Columbia's bowtie"
same here

2021-07-24 17:14 UTC, SgtHunk commented on code/FulpstationCode/halloween_costumes/2020/columbia.dm
> +	name = "Columbia's shoes"
and here

2021-07-24 17:14 UTC, SgtHunk commented on code/FulpstationCode/halloween_costumes/2020/daft_frank.dm
> +	dynamic_hair_suffix = ""
names should be subtle, also why are they hardhats, this doesn't overwrite the action types either

2021-07-24 17:14 UTC, SgtHunk commented on code/FulpstationCode/halloween_costumes/2020/daft_frank.dm
> +	name = "The suit"
lowercase

2021-07-24 17:14 UTC, SgtHunk commented on code/FulpstationCode/halloween_costumes/2020/daft_frank.dm
> +	name = "insert name here"
name

2021-07-24 17:14 UTC, SgtHunk commented on code/FulpstationCode/halloween_costumes/2020/daft_frank.dm
> +	name = "insert name here"
name

2022-10-29 09:59 UTC, GuillaumePrata commented
WTF do I still have this open? I blame Mith either way!!1!

2022-10-29 09:59 UTC, closed without merging