I now own this entire repository and your soul.
TheSwain/Fulpstation pull request #523
Opened 2021-07-21 05:46 UTC by JohnFulpWillard

## About The Pull Request

The time to strike is NOW

## Why It's Good For The Game

This is a military coup against TheSwain.

## Changelog
:cl:
add: Nothing don't worry about it :trollface: 
/:cl:

2021-07-21 06:16 UTC, SgtHunk commented
ided pr

2021-08-02 00:35 UTC, FernandoJ8 commented
Según todas las leyes conocidas 
de aviación, 


no hay camino una abeja 
debería ser capaz de volar. 


Sus alas son demasiado pequeñas para ponerse 
su pequeño cuerpo gordo de la tierra. 


La abeja, por supuesto, vuela de todos modos 


porque las abejas no se preocupan 
que gente piensa es imposible.

2021-08-02 00:40 UTC, JohnFulpWillard commented
> 
> 
> Según todas las leyes conocidas
> de aviación,
> 
> no hay camino una abeja
> debería ser capaz de volar.
> 
> Sus alas son demasiado pequeñas para ponerse
> su pequeño cuerpo gordo de la tierra.
> 
> La abeja, por supuesto, vuela de todos modos
> 
> porque las abejas no se preocupan
> que gente piensa es imposible.

english only server please delete your account. :/

2021-09-23 03:39 UTC, SgtHunk requested changes

2021-09-23 03:39 UTC, SgtHunk commented on .github/CODEOWNERS
> +/ @JohnFulpWillard
```suggestion
/ @JohnFulpWillard @SgtHunk 
```

2021-11-08 11:58 UTC, Nobelium-XVIII commented
Marked as stale

2022-02-11 21:47 UTC, JohnFulpWillard commented
@Samuuu3 any update on this?

2022-02-20 07:43 UTC, closed without merging